title: Title
url: https://carbontrading.gov.sg
favicon: /images/favicon1.png
colors:
  primary-color: "#35b0b5"
  secondary-color: "#4c739e"
  media-colors:
    - title: media-color-one
      color: "#399797"
    - title: media-color-two
      color: "#aa89d0"
    - title: media-color-three
      color: "#806d6c"
    - title: media-color-four
      color: "#e6eeaf"
    - title: media-color-five
      color: "#00838f"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d20es3h5b424gq.amplifyapp.com
prod: https://master.d20es3h5b424gq.amplifyapp.com
facebook-pixel: ""
shareicon: /images/carbontrading-logo.png
is_government: false
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: recent-updates
